os: linux
dist: bionic
language: minimal
stage:
  - build
  - e2e-test
  - publish

arch:
  - arm64
  - amd64
jobs:
  include:
    - name: build
      script: ./.ci/build.sh
    - name: e2e-test
      install: ./.ci/e2e-test/setup.sh
      if: tag IS present OR commit_message =~ /perform-e2e/
      script: ./.ci/e2e-test/test.sh
      env:
        - CHANGE_MINIKUBE_NONE_USER=true
        - MINIKUBE_WANTUPDATENOTIFICATION=false
        - MINIKUBE_WANTREPORTERRORPROMPT=false
        - MINIKUBE_HOME=$HOME
        - CHANGE_MINIKUBE_NONE_USER=true
        - KUBECONFIG=$HOME/.kube/config
    - name: publish
      script: ./.ci/publish.sh
